# version of docker-compose to use
version: "3"

# services:
    # # 'app' is the name of the service, which is referenced in the docker-compose run command:
    # #  docker-compose run app sh -c "django-admin.py startproject site ."
    # app:
    #     build:
    #         context: .
        
    #     # map port on our host to port on our container image
    #     ports:
    #         - "80:80"

    #     # maps volume from local machine into docker container image
    #     #  gets project updates into docker image in real-time
    #     volumes:
    #         - ./site:/site
            
    #     # command that runs the application in the docker container
    #     #  0.0.0.0 means all available ip addresses that run on the docker container
    #     command: >
    #         sh -c "python manage.py runserver 0.0.0.0:80"

services:
    web:
        build: .
        # command: >
        #     sh -c "python manage.py migrate 
        #     && python ./data/import_data.py ./data 
        #     && bokeh serve ./ui/BokehApps/dashboard_plot ./ui/BokehApps/historical_dashboard_plot ./ui/BokehApps/historical_solar_forecast ./ui/BokehApps/market_plot ./ui/BokehApps/solar_plot ./ui/BokehApps/estimates_table.py ./ui/BokehApps/probability_table.py ./ui/BokehApps/sliders.py ./ui/BokehApps/__init__.py --allow-websocket-origin 10.10.10.10 --address 127.0.0.1 
        #     && python manage.py runserver 10.10.10.10:80"
        command: >
            sh -c "bokeh serve
            ./ui/BokehApps/dashboard_plot
            ./ui/BokehApps/historical_dashboard_plot
            ./ui/BokehApps/historical_solar_forecast
            ./ui/BokehApps/market_plot
            ./ui/BokehApps/solar_plot
            ./ui/BokehApps/estimates_table.py
            ./ui/BokehApps/probability_table.py
            ./ui/BokehApps/sliders.py
            ./ui/BokehApps/__init__.py
            --allow-websocket-origin 10.10.10.10 --address 127.0.0.1 
            && python manage.py runserver 10.10.10.10:80"
        volumes:
            - .:/site
        ports:
            - "80:80"
