# The base image is often a plain Linux OS
# For first builds, use python:3.8.0. However, this will result in very large images
# The smaller, popular alpine base image has issues for Python builds:
#  https://pythonspeed.com/articles/alpine-docker-python/
FROM python:3.8-slim-buster
LABEL maintainer="NREL - Thermal Energy Systems R&D \
                  matthew.boyd@nrel.gov" \
      version="1.0.0"

ENV PYTHONUNBUFFERED 1

# See: http://www.djangocurrent.com/2018/02/docker-run-as-non-root-user.html

# Update and install some core Linux components
RUN pip install --upgrade pip
RUN apt-get -qq update
RUN apt-get -qq install gcc

# Install coinor-cbc solver for Pyomo (Windows uses cbc.exe)
RUN apt-get -qq install -y coinor-cbc

# Create a group and user, both named 'app', that this app will run as
RUN groupadd -r app && \
    useradd -r -g app -d /site -s /sbin/nologin -c "Docker image user" app

# Create a base directory, specify ownership by 'app' user and 'app' group, and
#  set this directory as WORKDIR
ENV SITE_DIR=/site/
RUN install -g app -o app -d ${SITE_DIR}
WORKDIR $SITE_DIR

# Copy files from current directory into image directory ${SITE_DIR},
#  specifying group and user ownership
COPY --chown=app:app . ${SITE_DIR}

# Set all sub-directory permissions the same as base directory so new
#  files and directory inherit from these sub-directories they're in
RUN find ${SITE_DIR} -type d -exec chmod g+s {} \;

# Set group write permission on base directory contents recursively
RUN chmod -R g+w ${SITE_DIR}

# Switch to user named 'app'
USER app

# Install requirements
RUN pip install -r ${SITE_DIR}/requirements.txt


# TODO?: Replicate a virtualenv, see here for why:  https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
# Also see: https://pythonspeed.com/articles/activate-conda-dockerfile/
# ENV VIRTUAL_ENV=/loredash
# RUN python -m venv $VIRTUAL_ENV
# ENV PATH="$VIRTUAL_ENV:$PATH"
