# version of docker-compose to use
version: "3"

# Explanation
# The container can only be accessed via 127.0.0.1
# Docker maps this host address to the internal container address according to the port
#   127.0.0.1:8000 -> 10.10.10.10:8000  (or whatever target container port the host port is mapped to)
#   127.0.0.1:5006 -> 10.10.10.11:5006  (for the bokeh server)
# The --address and --port in the bokeh serve command are where the bokeh server is in the container
# The IPs and ports in /loredash/ui/views.py are what Django is using to try and reach the bokeh server.
# Django requests/polling seem to be leaving the container and re-entering. Therefore, the Django
#  requests/polls appear to be coming from 127.0.0.1:8000 (outside the container) and should thus target
#  the bokeh server at 127.0.0.1:5006 (which gets mapped to 10.10.10.11:5006 once back in the container).

services:
    # this is an 'app' from which a container is created. 'plots' is another app and will be another container
    dash:
        image: dquintan/lore
        networks:
            app_net:
                ipv4_address: 10.10.10.10
        command: python manage.py runserver 0.0.0.0:8000
        container_name: dashboard
        # Mapping to a volume may be causing a problematic local dependency on manage.py
        # volumes:
        #     - .:/loredash
        ports:
            # HOST_PORT:CONTAINER_PORT ('host' is the computer hosting the container)
            - "8000:8000"
        # depends_on makes sure commands are executed in the correct order
        depends_on:
            - migration
            - plots
    plots:
        image: dquintan/lore
        networks:
            app_net:
                ipv4_address: 10.10.10.11
        command: >
            sh -c "python -m bokeh serve
            ./ui/BokehApps/dashboard_plot
            ./ui/BokehApps/historical_dashboard_plot
            ./ui/BokehApps/historical_solar_forecast
            ./ui/BokehApps/market_plot
            ./ui/BokehApps/solar_plot
            ./ui/BokehApps/estimates_table.py
            ./ui/BokehApps/probability_table.py
            ./ui/BokehApps/sliders.py
            ./ui/BokehApps/__init__.py
            --allow-websocket-origin 127.0.0.1:8000 --address 10.10.10.11 --port 5006"
        #   allow connections from IP:PORT, and host plotting server on IP and PORT
        container_name: plotting_server
        # Also not mapping to a local volume here as well
        # volumes:
        #     - .:/loredash
        ports:
            # Networked service-to-service communication uses the CONTAINER_PORT.
            # When HOST_PORT is defined, the service is accessible outside the swarm as well.
            # see: https://docs.docker.com/compose/networking/
            - "5006:5006"
        depends_on:
            - migration
    migration:
        build: .
        image: dquintan/lore
        networks:
            - app_net
        command: python manage.py migrate
        container_name: migration
        # Mapping to a volume may be causing a problematic local dependency on manage.py
        # volumes:
        #     - .:/loredash

networks:
    app_net:
        driver: bridge
        # Removing for greater compatibility across systems
        # enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 10.10.10.0/24
        # Removing for greater compatibility across systems
        #          gateway: 10.10.10.254
