# Generated by Django 2.2.2 on 2021-02-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDataRTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('actual', models.FloatField(default=None, verbose_name='Actual [MWe]')),
                ('optimal', models.FloatField(default=None, verbose_name='Optimal [MWe]')),
                ('scheduled', models.FloatField(default=None, verbose_name='Scheduled [MWe]')),
                ('field_operation_generated', models.FloatField(default=None, verbose_name='Field Operation Generated [MWt]')),
                ('field_operation_available', models.FloatField(default=None, verbose_name='Field Operation Available [MWt]')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastsMarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('market_forecast', models.FloatField(default=None, verbose_name='Market Forecast [-]')),
                ('ci_plus', models.FloatField(default=None, verbose_name='CI+ [%]')),
                ('ci_minus', models.FloatField(default=None, verbose_name='CI- [%]')),
            ],
        ),
    ]
