# Generated by Django 2.2.2 on 2021-07-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardDataRTO',
        ),
        migrations.DeleteModel(
            name='ForecastsMarketData',
        ),
    ]
