# Generated by Django 2.2.2 on 2020-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddatarto',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='forecastsmarketdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='forecastssolardata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp'),
        ),
    ]
