# Generated by Django 2.2.2 on 2020-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20201021_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastsmarketdata',
            name='market_forecast',
            field=models.FloatField(default=None, verbose_name='Market Forecast [-]'),
        ),
    ]
