# Generated by Django 2.2.2 on 2021-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarForecastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_made', models.DateTimeField(db_index=True, verbose_name='Forecast Made')),
                ('forecast_for', models.DateTimeField(db_index=True, verbose_name='Forecast For')),
                ('clear_sky', models.FloatField(default=None, verbose_name='Clear Sky [W/m2]')),
                ('ratio', models.FloatField(default=None, verbose_name='Ratio [Predicted/Clear Sky]')),
            ],
        ),
        migrations.CreateModel(
            name='TechData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestep end')),
                ('E_tes_charged', models.FloatField(default=None, verbose_name='TES charge state [kWht]')),
                ('eta_tower_thermal', models.FloatField(default=None, verbose_name='Tower thermal efficiency [-]')),
                ('eta_field_optical', models.FloatField(default=None, verbose_name='Field optical efficiency [-]')),
                ('W_grid_no_derate', models.FloatField(default=None, verbose_name='Power to grid without derate [kWe]')),
                ('tou', models.FloatField(default=None, verbose_name='TOU value [-]')),
                ('W_grid_with_derate', models.FloatField(default=None, verbose_name='Power to grid with derate [kWe]')),
                ('Q_tower_incident', models.FloatField(default=None, verbose_name='Tower incident thermal power [kWt]')),
                ('Q_field_incident', models.FloatField(default=None, verbose_name='Field incident thermal power [kWt]')),
                ('pricing_multiple', models.FloatField(default=None, verbose_name='Pricing multiple [-]')),
                ('dni', models.FloatField(default=None, verbose_name='DNI [W/m2]')),
                ('Q_tower_absorbed', models.FloatField(default=None, verbose_name='Tower HTF heat rate [kWt]')),
                ('mdot_tower', models.FloatField(default=None, verbose_name='Tower HTF mass flow rate [kg/s]')),
                ('mdot_cycle', models.FloatField(default=None, verbose_name='Cycle HTF mass flow rate [kg/s]')),
            ],
        ),
    ]
