# Generated by Django 2.2.2 on 2020-10-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PysamTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('P_out_net', models.FloatField(default=None, verbose_name='P_out_net [MWe]')),
            ],
        ),
    ]
