# Generated by Django 2.2.2 on 2021-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStateData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestep end')),
                ('is_field_tracking', models.FloatField(default=None, verbose_name='Is field tracking? [-]')),
                ('receiver_mode', models.FloatField(default=None, verbose_name='Receiver operating mode [-]')),
                ('dt_rec_startup_remain', models.FloatField(default=None, verbose_name='Receiver startup time remaining [hr]')),
                ('dE_rec_startup_remain', models.FloatField(default=None, verbose_name='Receiver startup energy remaining [kWh]')),
                ('dt_rec_current_mode', models.FloatField(default=None, verbose_name="Time receiver's been in current state [hr]")),
                ('dt_rec_not_on', models.FloatField(default=None, verbose_name="Time receiver's not been on (off or startup) [hr]")),
                ('sf_adjust', models.FloatField(default=None, verbose_name='Solar field percent unavailable (latest) [%]')),
                ('T_cold_tank', models.FloatField(default=None, verbose_name='Cold tank temperature [C]')),
                ('T_hot_tank', models.FloatField(default=None, verbose_name='Hot tank temperature [C]')),
                ('Frac_avail_hot_tank', models.FloatField(default=None, verbose_name='Fraction of available storage in hot tank [%]')),
                ('cycle_mode', models.FloatField(default=None, verbose_name='Initial cycle operating mode [-]')),
                ('dt_cycle_startup_remain', models.FloatField(default=None, verbose_name='Cycle startup time remaining [hr]')),
                ('dE_cycle_startup_remain', models.FloatField(default=None, verbose_name='Cycle startup energy remaining [kWh]')),
                ('dt_cycle_current_mode', models.FloatField(default=None, verbose_name="Time cycle's been in current state [hr]")),
                ('dt_cycle_not_on', models.FloatField(default=None, verbose_name="Time cycle's not been on (off, startup, or standby) [hr]")),
                ('W_cycle', models.FloatField(default=None, verbose_name='Cycle electricity generation [kWe]')),
                ('Q_cycle', models.FloatField(default=None, verbose_name='Cycle thermal input [kWt]')),
            ],
        ),
    ]
