# Generated by Django 2.2.2 on 2021-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0002_plantstatedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestep end')),
                ('dni', models.FloatField(default=None, verbose_name='Direct normal irradiance [W/m2]')),
                ('dhi', models.FloatField(default=None, verbose_name='Diffuse horizontal irradiance [W/m2]')),
                ('ghi', models.FloatField(default=None, verbose_name='Global horizontal irradiance [W/m2]')),
                ('dew_point', models.FloatField(default=None, verbose_name='Dew point [C]')),
                ('temperature', models.FloatField(default=None, verbose_name='Ambient dry bulb temperature [C]')),
                ('pressure', models.FloatField(default=None, verbose_name='Ambient atmospheric pressure [mbar]')),
                ('wind_direction', models.FloatField(default=None, verbose_name='Horizontal wind direction [deg]')),
                ('wind_speed', models.FloatField(default=None, verbose_name='Horizontal wind speed [m/s]')),
            ],
        ),
    ]
