# Generated by Django 2.2.2 on 2021-07-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0003_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantstatedata',
            name='dt_cycle_current_mode',
        ),
        migrations.RemoveField(
            model_name='plantstatedata',
            name='dt_cycle_not_on',
        ),
        migrations.RemoveField(
            model_name='plantstatedata',
            name='dt_rec_current_mode',
        ),
        migrations.RemoveField(
            model_name='plantstatedata',
            name='dt_rec_not_on',
        ),
    ]
