# Generated by Django 2.2.2 on 2021-07-12 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0004_auto_20210706_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarforecastdata',
            name='forecast_for',
        ),
        migrations.RemoveField(
            model_name='solarforecastdata',
            name='forecast_made',
        ),
        migrations.RemoveField(
            model_name='solarforecastdata',
            name='id',
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dhi',
            field=models.FloatField(default=None, verbose_name='Diffuse horizontal irradiance [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni',
            field=models.FloatField(default=None, verbose_name='Direct normal irradiance [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni_10',
            field=models.FloatField(default=None, verbose_name='Clear Sky 10% probability [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni_25',
            field=models.FloatField(default=None, verbose_name='Clear Sky 25% probability [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni_50',
            field=models.FloatField(default=None, verbose_name='Clear Sky 50% probability [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni_75',
            field=models.FloatField(default=None, verbose_name='Clear Sky 75% probability [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni_90',
            field=models.FloatField(default=None, verbose_name='Clear Sky 90% probability [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='ghi',
            field=models.FloatField(default=None, verbose_name='Global horizontal irradiance [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='temperature',
            field=models.FloatField(default=None, verbose_name='Ambient dry bulb temperature [C]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 21, 0, 6, 657403, tzinfo=utc), primary_key=True, serialize=False, verbose_name='Timestep end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='wind_speed',
            field=models.FloatField(default=None, verbose_name='Horizontal wind speed [m/s]'),
        ),
    ]
