# Generated by Django 2.2.2 on 2021-02-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mediation', '0004_auto_20201125_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Plant name')),
                ('latitude', models.FloatField(default=None, verbose_name='Latitude, degrees North [deg]')),
                ('longitude', models.FloatField(default=None, verbose_name='Longitude, degrees East [deg]')),
                ('elevation', models.FloatField(default=None, verbose_name='Elevation above sea level [m]')),
                ('timezone', models.FloatField(default=None, verbose_name='Timezone, UTC offset [hr]')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
        ),
    ]
