# Generated by Django 2.2.2 on 2021-07-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0004_auto_20210706_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecastdata',
            name='dhi',
            field=models.FloatField(default=None, verbose_name='Diffuse horizontal irradiance [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='dni',
            field=models.FloatField(default=None, verbose_name='Direct normal irradiance [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='ghi',
            field=models.FloatField(default=None, verbose_name='Global horizontal irradiance [W/m2]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='temperature',
            field=models.FloatField(default=None, verbose_name='Ambient dry bulb temperature [C]'),
        ),
        migrations.AddField(
            model_name='solarforecastdata',
            name='wind_speed',
            field=models.FloatField(default=None, verbose_name='Horizontal wind speed [m/s]'),
        ),
    ]
