# Generated by Django 2.2.2 on 2021-07-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0005_auto_20210712_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecastdata',
            name='pressure',
            field=models.FloatField(default=None, verbose_name='Ambient atmospheric pressure [mbar]'),
        ),
    ]
