# Generated by Django 2.2.2 on 2021-02-03 15:14

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0006_auto_20210203_1429'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plantconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
