# Generated by Django 2.2.2 on 2021-02-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediation', '0007_auto_20210203_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantconfig',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
